name: soundpool_web
description: A Flutter Sound Pool for playing short audio files. Sound tracks are cached in memory and played directly from cache.
homepage: https://github.com/ukasz123/soundpool/tree/master/soundpool_web
version: 2.4.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"
  
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.1.0
  soundpool_platform_interface:
    git:
      url: https://github.com/lotum/soundpool.git
      ref: fork-v2
      path: soundpool_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: SoundpoolPlugin
        fileName: soundpool_web.dart
