name: soundpool
description: A Flutter Sound Pool for playing short audio files. Sound tracks are cached in memory and played directly from cache.
homepage: https://github.com/ukasz123/soundpool/tree/master/soundpool
version: 2.4.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  soundpool_platform_interface:
    git:
      url: https://github.com/lotum/soundpool.git
      ref: fork-v0
      path: soundpool_platform_interface
  soundpool_macos:
    git:
      url: https://github.com/lotum/soundpool.git
      ref: fork-v0
      path: soundpool_macos
  soundpool_web:
    git:
      url: https://github.com/lotum/soundpool.git
      ref: fork-v0
      path: soundpool_web

flutter:
  plugin:
    platforms:
      android:
        package: pl.ukaszapps.soundpool
        pluginClass: SoundpoolPlugin
      ios:
        pluginClass: SoundpoolPlugin
      web:
        default_package: soundpool_web
      macos:
        default_package: soundpool_macos
