name: soundpool_platform_interface
description: A common platform interface for the soundpool plugin.
homepage: https://github.com/ukasz123/soundpool/tree/master/soundpool_platform_interface
version: 2.3.0+2
dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
